### ISSUE TITLE
Game fails to launch after the very recent update.

### ISSUE THREAD

**Issue by NaterEST** [Rosalie241/SporeModLoader#1]
Since there is now a small team on Spore again, just about an hour or so ago, the game got an update. When launching it with SporeModLoader installed, it'll give the next 2 errors after each other:
![2024-10-23_23-12](https://github.com/user-attachments/assets/316180e9-5974-4edc-8e54-dbd2f607e3d5)
![2024-10-23_23-12](https://github.com/user-attachments/assets/3d78a8d5-bb5e-4424-a341-3b3982d52371)

**Comment by Rosalie241** [comment]
I've now added support for the October 2024 version of Spore in the latest release (v3.2.2), though I'll mention that the Steam version currently does **not** work yet because the executable is obfuscated, which EA will fix soon.

The GOG version of the latest update will work fine for it because that executable isn't obfuscated, so if you're using the Steam version of Spore then I'd recommend waiting for an update before using SporeModLoader v3.2.2.

I'll close this issue once EA updates the Steam version of Spore to match the GOG version's executable.

**Comment by NaterEST** [comment]
Thanks for the update. I am using the steam version, do I'll likely have to wait a lil longer :)

**Comment by Rosalie241** [comment]
It seems that EA wont remove the DRM afterall sadly, the higher ups aren't bulging on the issue.

There are 2 options for Steam users, they can either downgrade the exe by downloading the older depot and replace the exe, alongside installing SporeFixOnline to make online functionality work again, which can be achieved with the following:

1) Press Win + R, and type in `steam://open/console/` to open Steam's console (or open the steam console another way, i.e Linux might need another method)
2) From there, type `download_depot 24720 24721 7407510787032991484` into the console to prompt Steam to download the old version.
3) When it's installed, it **will not** be in the default location but instead in `Steam/Steamapps/Content/`, and you can safely copy over the EXE file.

Or they can unpack the executable using [SteamLess](https://github.com/atom0s/Steamless), though SporeModLoader doesn't support that unpacked executable yet but I can add support for it if you want to go that route.

I'll try to add a note for this to the README soon aswell, and I do apologize it took me a while to reply.

**Comment by NaterEST** [comment]
will try that. So I just replace the exe?

**Comment by NaterEST** [comment]
Using linux, I have the Steam Console enabled via the command-line options, but I also have SteamDepotDownloader

**Comment by Rosalie241** [comment]
> will try that. So I just replace the exe?

Correct, the one in the `SporebinEP1` directory

**Comment by NaterEST** [comment]
So, SporeFixOnline doesn't seem to work with the previous version of the game (pre October 2024 update).

**Comment by NaterEST** [comment]
every other mod I've installed works, except SporeFixOnline for some reason :/

**Comment by Rosalie241** [comment]
> So, SporeFixOnline doesn't seem to work with the previous version of the game (pre October 2024 update).

It should, it stopped working 2 days ago but I've fixed that with the latest update of SporeFixOnline, I've also fixed WINE compatability, can you try it again with the latest version?

**Comment by NaterEST** [comment]
I've now tried the latest version, work prefectly now.

**Comment by Rosalie241** [comment]
I'm glad it works now :heart:

**Comment by Rosalie241** [comment]
I've added support for the steam version without downgrading here: https://github.com/Rosalie241/SporeModLoader/actions/runs/12561544206

**Comment by NaterEST** [comment]
nice, I'll check this out when I get home
